require "yajl"
require "open-uri"
require "thor"

require "xbox-api/version"
require "xbox-api/client"
require "xbox-api/gamer"
require "xbox-api/game"
require_relative "./xbox-api/xboxlive"
# require "xbox-api/xboxlive"
